env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
parserOptions:
  ecmaVersion: 12
plugins:
  - vue
rules:
  curly: warn
  semi-spacing:
    - error
    - before: false
      after: true
  space-before-blocks:
    - warn
    - functions: always
  vue/require-prop-types: 0
  vue/require-default-prop: 0
  no-unused-vars: off
globals:
  __dirname: true

